name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    name: Hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: secret
        env:
          GA_CONFIG_1: ${{secrets.GA_CONFIG_1}}
          GA_CONFIG_2: ${{secrets.GA_CONFIG_2}}
          GA_SRC: ${{secrets.GA_SRC}}
          LIFF_ID: ${{secrets.LIFF_ID}}
        run: |
　　　　　##access to $LIFF_ID if this script is bash
